[package]
name = "piston-example"
version = "0.1.0"
authors = ["chrisk_24 <chrisknappers@hotmail.com>"]


[dependencies]
piston = "0.37.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.47.0"
piston2d-opengl_graphics = "0.53.0"
image = "0.19.0"
rand = "0.5.5"
tinyfiledialogs = "3.3.5"
